name: Build & Push Docker Image to DockerHub

on:
    workflow_call:
        inputs:
            use_lfs_cache:
                description: 'Cache and retrieve Github LFS objects to reduce LFS bandwidth.'
                required: false
                type: boolean
                default: false

jobs:
    extract-branch-name-safe:
        runs-on: ubuntu-latest
        outputs:
            branch_name_safe: ${{ steps.branch-names-safe.outputs.branch_name_safe }}
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4
                with:
                    submodules: 'recursive'
                    lfs: true
            
            -   name: Extract Branch Name
                id: branch-names
                uses: ammortal-inc/branch-names@v8
            
            -   name: Make Branch Name Safe
                id: branch-names-safe
                run: |
                    # Get current branch
                    BRANCH_NAME="${{steps.branch-names.outputs.current_branch}}"
                    # Replace slash with underscore
                    BRANCH_NAME_SAFE="${BRANCH_NAME//\//_}"
                    # Save new name as output variable of this job
                    echo "branch_name_safe=${BRANCH_NAME_SAFE}" >> "$GITHUB_OUTPUT"

    build-push-docker-image:
        runs-on: ubuntu-latest
        needs: extract-branch-name-safe
        steps:

            -   name: Checkout Repository
                uses: actions/checkout@v4
                with:
                    submodules: 'recursive'
                    lfs: true

            -   name: Create LFS file list
                if: ${{ inputs.use_lfs_cache }}
                run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

            -   name: LFS Cache
                uses: actions/cache@v4
                if: ${{ inputs.use_lfs_cache }}
                with:
                    path: .git/lfs/objects
                    key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
                    restore-keys: |
                        ${{ runner.os }}-lfs-

            -   name: Checkout LFS
                run: git lfs pull

            -   name: Login to DockerHub  
                uses: docker/login-action@v3
                with: 
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_READ_WRITE }}
                
            -   name: Print Image Name
                run: |
                    echo "Building image ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.extract-branch-name-safe.outputs.branch_name_safe }} ..."

            -   name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    platforms: linux/arm64

            -   name: Build and Push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    platforms: linux/arm64
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.extract-branch-name-safe.outputs.branch_name_safe }}