name: Build & Push Docker Image to DockerHub

on:
    workflow_call:
        inputs:
            use_lfs_cache:
                description: 'Cache and retrieve Github LFS objects to reduce LFS bandwidth.'
                required: false
                type: boolean
                default: false

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest
        steps:

            -   name: Checkout Repository
                uses: actions/checkout@v4
                with:
                    submodules: 'recursive'
                    lfs: true

            -   name: Create LFS file list
                if: ${{ inputs.use_lfs_cache }}
                run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

            -   name: LFS Cache
                uses: actions/cache@v4
                if: ${{ inputs.use_lfs_cache }}
                with:
                    path: .git/lfs/objects
                    key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
                    restore-keys: |
                        ${{ runner.os }}-lfs-

            -   name: Checkout LFS
                run: git lfs pull

            -   name: Extract Branch Name
                id: branch-names
                uses: ammortal-inc/branch-names@v8
            
            -   name: Make Branch Name Safe
                id: branch-names-safe
                run: |
                    # Get current branch
                    CURRENT_BRANCH="${{steps.branch-names.outputs.current_branch}}"
                    # Replace slash with underscore
                    CURRENT_BRANCH_SAFE="${CURRENT_BRANCH//\//_}"
                    # # Make all lowercase
                    # CURRENT_BRANCH_SAFE="${CURRENT_BRANCH_SAFE,,}"
                    # Save new name as output variable of this job
                    echo "current_branch_safe=${CURRENT_BRANCH_SAFE}" >> "$GITHUB_OUTPUT"

            -   name: Print Image Name
                run: |
                    echo "Building image ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.branch-names-safe.outputs.current_branch_safe }} ..."

            -   name: Login to DockerHub  
                uses: docker/login-action@v3
                with: 
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_READ_WRITE }}
                
            -   name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    platforms: linux/arm64

            -   name: Build and Push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    platforms: linux/arm64
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.branch-names-safe.outputs.current_branch_safe }}